<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = [
            // Users with C-Level roles
            [
                'first_name' => 'Alice',
                'last_name' => 'Johnson',
                'email' => 'alice.johnson@example.com',
                'instagram' => 'alice_insta',
                'linkedin' => 'alice-linkedin',
                'batch_no' => 1,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => 1, // Chief Creative Officer
                'division_id' => null, // No division for C-Level
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => true,
                'Sflag' => false,
                'StFlag' => false,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Bob',
                'last_name' => 'Smith',
                'email' => 'bob.smith@example.com',
                'instagram' => 'bob_insta',
                'linkedin' => 'bob-linkedin',
                'batch_no' => 1,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => 2, // Chief Development Officer
                'division_id' => null, // No division for C-Level
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => true,
                'Sflag' => false,
                'StFlag' => false,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Users with Division roles
            [
                'first_name' => 'Charlie',
                'last_name' => 'Brown',
                'email' => 'charlie.brown@example.com',
                'instagram' => 'charlie_insta',
                'linkedin' => 'charlie-linkedin',
                'batch_no' => 2,'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 1, // Social Media Specialist
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Diana',
                'last_name' => 'Prince',
                'email' => 'diana.prince@example.com',
                'instagram' => 'diana_insta',
                'linkedin' => 'diana-linkedin',
                'batch_no' => 2,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 6,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => true,
                'StFlag' => false,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Staf',
                'last_name' => 'Makan',
                'email' => 'staff-1@example.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 2,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 3, // Content Writer
                'supervisor_id' => 4,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                
                'first_name' => 'William',
                'last_name' => 'Tukien',
                'email' => 'staff-2@example.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 2,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 3, // Content Writer
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => true,
                'StFlag' => false,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Admin',
                'last_name' => '1',
                'email' => 'admin.weekly.report@yopmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => null, // Content Writer
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => true,
                'Sflag' => true,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Start Real Data
            // C-Level CTO
            [
                'first_name' => 'Fabian Juliansyah',
                'last_name' => 'Cahyadi',
                'email' => 'fabianjuliansyah89@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => 6, // C-Level ID 6
                'division_id' => null, // No specific division
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => true, // CFlag set to true
                'Sflag' => false,
                'StFlag' => false,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // C-Level CPD
            [
                'first_name' => 'Salma Benani',
                'last_name' => 'Sudewaji',
                'email' => 'salmabenanis@upi.edu',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'), // Default password
                'email_verified_at' => Carbon::now(),
                'c_level_id' => 4, // C-Level ID 4
                'division_id' => null, // No specific division
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => true, // CFlag set to false by default
                'Sflag' => false,
                'StFlag' => false,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Ni Komang Regina Ary',
                'last_name' => 'Shanty',
                'email' => 'reginaaryshanty@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'), // Default password
                'email_verified_at' => Carbon::now(),
                'c_level_id' => 4, // C-Level ID 4
                'division_id' => null, // No specific division
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => true, // CFlag set to false by default
                'Sflag' => false,
                'StFlag' => false,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Staff CPD
            // Talent Engagement
            [
                'first_name' => 'Alia Destari',
                'last_name' => 'Putri',
                'email' => 'destarialia54@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 7,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => true,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => false,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Nisrina Qonita',
                'last_name' => 'Al-Husna',
                'email' => 'nisrinaqonitalh@upi.edu',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 7,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => true,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => false,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Lailatul',
                'last_name' => 'Fitria',
                'email' => 'lailatulfitria212@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 7,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Lina Fauziah',
                'last_name' => "Mas'ud",
                'email' => 'linafauziah128@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 7,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Mesa Dwi',
                'last_name' => 'Nurianto',
                'email' => 'nuriantomesa@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 7,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Rachma Adinda',
                'last_name' => 'Putri',
                'email' => 'rachmaadinda.rap@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 7,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Salma Salsabila',
                'last_name' => 'Hadi',
                'email' => 'salmasalsabilahadi.work@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 7,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Maria Adelitha',
                'last_name' => 'Liseana',
                'email' => 'mariadelithaliseana@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 7,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Mutiara Khairunnisa',
                'last_name' => 'Mulyono',
                'email' => 'mutiarakhairunnisamulyono@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 7,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Fildzah',
                'last_name' => 'Zahidah',
                'email' => 'fildzahznaa@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 7,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // People and Culture
            [
                'first_name' => 'Meilisa',
                'last_name' => 'Nuranjani',
                'email' => 'melisanuranjani@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 8,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => true,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => false,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Laila',
                'last_name' => 'Az Zahra',
                'email' => 'laila.azzahra616@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 8,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => true,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => false,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Andhara Myeisha',
                'last_name' => 'Kalila',
                'email' => 'andharakalila@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 8,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Talitha Eka',
                'last_name' => 'Purwanto',
                'email' => 'ekataliya@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 8,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Rifa Salsabila',
                'last_name' => 'Anggraeni',
                'email' => 'salsaraeni.06@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 8,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Shelvira Gisty',
                'last_name' => 'Rachmadanti',
                'email' => 'selviragisty@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 8,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Zulfin',
                'last_name' => 'Fahrina',
                'email' => 'vivinfahrina@students.unnes.ac.id',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 8,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Lutfiana Alfa',
                'last_name' => 'Riddhoh',
                'email' => 'lutfiana.alfa@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 8,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Lisa',
                'last_name' => 'Herdiyanti',
                'email' => 'lisaherdiyanti83@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 8,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Risna',
                'last_name' => 'Mardiana',
                'email' => 'mardianarisna11@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 8,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Fadliah Tri',
                'last_name' => 'Kusnanda',
                'email' => 'fadliahtrikusnanda@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 8,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Secretary
            [
                'first_name' => 'Afifah Rizqi',
                'last_name' => 'Septiyanawati',
                'email' => 'afifahspt09@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 9,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => true,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => false,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Indah Himawat',
                'last_name' => 'Pertiwi',
                'email' => 'indah3pertiwi@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 9,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => true,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => false,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Allyah Putri',
                'last_name' => 'Dwiyana',
                'email' => 'allyah31putri@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 9,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Amelia',
                'last_name' => 'Pratiwi',
                'email' => '01ameliapratiwiii@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 9,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Karissa Aghnia',
                'last_name' => 'Rubby',
                'email' => 'issaaghnia@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 9,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Jessica Anggrina',
                'last_name' => 'Yunan Devona',
                'email' => 'devonajessica2@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 9,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Brand Ambassador Supervisor
            [
                'first_name' => 'Ceisya Frederica',
                'last_name' => 'Raubun',
                'email' => 'ceisyaraubun05@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 10,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => true,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => false,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Retno Anggita',
                'last_name' => 'Saraswati',
                'email' => 'anggitasaraswati344@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 10,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => true,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => false,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Najma',
                'last_name' => 'Auly',
                'email' => 'najmaulyy23@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 10,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Muhammad Fajar',
                'last_name' => 'Fachturahman',
                'email' => '6662210026@untirta.ac.id',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 10,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Inna Asilni',
                'last_name' => 'Rahmawati',
                'email' => 'innaasilni19@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 10,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Talitha Alysia',
                'last_name' => 'Nabilah',
                'email' => 'talithaalyna@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null,
                'division_id' => 10,
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true,
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Staff CTO
            // Web Design
            [
                'first_name' => 'Muhammad Ilham',
                'last_name' => 'Takbir',
                'email' => 'muhamad.ilham.takbir24@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 13, // Division ID 13
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => true,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => false, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Dheivani Senjadipa',
                'last_name' => 'Senjadipa',
                'email' => 'dheivanisenja09@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 13, // Division ID 13
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => true,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => false, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Daffa Umar Thalib',
                'last_name' => 'Thalib',
                'email' => 'daffaumart@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 13, // Division ID 13
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Karimah Khairunnisa A',
                'last_name' => 'Khairunnisa A',
                'email' => 'karimahkhaerunnisa@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 13, // Division ID 13
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Muhammad Zamzam Fauzan',
                'last_name' => 'Fauzan',
                'email' => 'mhmmdzamzamfauzan@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 13, // Division ID 13
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Gabrielind Yoefita Aryanta Gultom',
                'last_name' => 'Gultom',
                'email' => 'g.yoefita@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 13, // Division ID 13
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Ferry Kurniawan',
                'last_name' => 'Kurniawan',
                'email' => 'fferrykurniawann@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 13, // Division ID 13
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Frontend Developer
            [
                'first_name' => 'Alif Essa',
                'last_name' => 'Nurcahyani',
                'email' => 'alifessanurcahyani@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 14, // Division ID 14
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => true,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => false, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Edu Juanda',
                'last_name' => 'Pratama',
                'email' => 'edu.123320012@student.itera.ac.id',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 14, // Division ID 14
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => true,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Bima Dharma',
                'last_name' => 'Yahya',
                'email' => 'bimadharmayahya@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 14, // Division ID 14
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Reygan',
                'last_name' => 'Fadhilah',
                'email' => 'fadhilahreygan@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 14, // Division ID 14
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Vyrra',
                'last_name' => 'Fitriana',
                'email' => 'vyrra.hartanto@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 14, // Division ID 14
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Muhammad',
                'last_name' => 'Fauzan',
                'email' => 'm.fauzan.hb@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 14, // Division ID 14
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // David Developer
            [
                'first_name' => 'David',
                'last_name' => 'Dwiyanto',
                'email' => 'daviddwiyanto.student@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 15, // Division ID 15
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => true,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => false, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Dimas Deo',
                'last_name' => 'Rezkidyo',
                'email' => 'dimasrdyo@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 15, // Division ID 15
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => true,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => false, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Ahmad Sofi',
                'last_name' => 'Sidik',
                'email' => 'sofi.sidik12@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 15, // Division ID 15
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Rengga Rendi',
                'last_name' => 'Saputra',
                'email' => 'renggarendy22@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 15, // Division ID 15
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Quality Assurance
            [
                'first_name' => 'Falah',
                'last_name' => 'Shalahuddin',
                'email' => 'falahshalahuddin@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 16, // Division ID 16
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => true,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => false, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Nadindra Maulana',
                'last_name' => 'Aziz',
                'email' => 'maulananadindra@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 16, // Division ID 16
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Ravita Nurul',
                'last_name' => 'Asmi',
                'email' => 'ravitanrl@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 16, // Division ID 16
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // DevOps
            [
                'first_name' => 'Della',
                'last_name' => 'Setyowati',
                'email' => 'dellastywt5@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 17, // Division ID 17
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => true,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => false, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'first_name' => 'Ananda Andreas',
                'last_name' => 'Dharma',
                'email' => 'anandaandreas11@gmail.com',
                'instagram' => 'https://www.instagram.com/candidate.college',
                'linkedin' => 'https://www.linkedin.com/company/candidate-college',
                'batch_no' => 5,
                'number' => '62123',
                'password' => Hash::make('password123'),
                'email_verified_at' => Carbon::now(),
                'c_level_id' => null, // Not a C-Level
                'division_id' => 17, // Division ID 17
                'supervisor_id' => null,
                'vice_supervisor_id' => null,
                'HFlag' => false,
                'ChFlag' => false,
                'CFlag' => false,
                'Sflag' => false,
                'StFlag' => true, // StFlag set to true
                'profile_picture' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];

        DB::table('users')->insert($users);
    }
}