services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-app
        volumes:
            - ./:/var/www/html
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        depends_on:
            - db

    web:
        image: nginx:alpine
        container_name: nginx-web
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: freedb_DB_EXPERIMENT
            MYSQL_USER: freedb_USER_TESTING_STAGING
            MYSQL_PASSWORD: jt22fWBgJ!Fz53T
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root_password
        ports:
            - "8081:80"
        networks:
            - app-network
        depends_on:
            - db

networks:
    app-network:
        driver: bridge

volumes:
    db-data:
